import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { mapHostSource } from './map-host-source'

const appFile = (path: string) => readFileSync(fileURLToPath(new URL(`../app/${path}`, import.meta.url)), 'utf8')

describe('mobile GIS interface', () => {
  it('hydrates the map directly with the same SSR and client root node', () => {
    const shell = appFile('components/layout/AppShell.vue')
    expect(shell).toContain('<LazyMapCanvas />')
    expect(shell).not.toContain('hydrate-on-idle')
  })

  it('uses the shared header token and defines mobile, compact and desktop workbench stages', () => {
    const shell = appFile('components/layout/AppShell.vue')
    const css = appFile('assets/css/main.css')
    expect(css).toContain('--app-header-height: 4rem')
    expect(shell).toContain('height: calc(100dvh - var(--app-header-height))')
    expect(shell).toContain('(min-width: 900px) and (max-width: 1279px) and (min-height: 560px)')
    expect(shell).toContain('@media (min-width: 1280px)')
    expect(shell).toContain('xl:hidden')
    expect(shell).toContain('env(safe-area-inset-bottom)')
  })

  it('renders filter and selection once for both sheet and side panel', () => {
    const shell = appFile('components/layout/AppShell.vue')
    const content = appFile('components/layout/GisPanelContent.vue')
    const map = mapHostSource()
    const sheetUses = shell.match(/<AppBottomSheet/g) || []
    expect(sheetUses).toHaveLength(1)
    expect(shell).toContain('aria-label="Filter öffnen"')
    expect(shell).not.toContain('aria-label="Analyse öffnen"')
    expect(shell).toContain(':title="activePanelTitle"')
    expect(shell).toContain(':open="isMobile && mapStore.activeGisPanel !== null"')
    expect(shell).toContain('v-if="isCompact && mapStore.activeGisPanel !== null"')
    expect(content).toContain("mapStore.activeGisPanel === 'filter'")
    expect(content).not.toContain("mapStore.activeGisPanel === 'analytics'")
    expect(content).toContain("mapStore.activeGisPanel === 'selection'")
    expect(content).not.toContain("mapStore.activeGisPanel === 'assistant'")
    expect(shell.match(/initial-snap="medium"/g)).toHaveLength(1)
    expect(content).toContain('<MapSelectionContent embedded')
    expect(shell).not.toContain('<Drawer')
    expect(content).toContain('filterStore.reset')
    expect(map).not.toContain('polygonPreviewOpen')
    expect(map).toContain("mapStore.openGisPanel('selection')")
  })

  it('keeps the embedded filter in the shared panel scroll flow', () => {
    const content = appFile('components/layout/GisPanelContent.vue')
    const filter = appFile('components/layout/LeftSidebar.vue')
    expect(content).toContain('<LazyLeftSidebar embedded')
    expect(filter).toContain('data-filter-summary')
    expect(filter).toContain("compact ? 'border-b border-slate-200 px-1 pb-3'")
    expect(filter).toContain('<div v-if="!embedded"')
  })

  it('uses one mutually exclusive GIS panel state across mobile and compact layouts', () => {
    const store = appFile('stores/map.ts')
    const shell = appFile('components/layout/AppShell.vue')
    expect(store).toContain("export type GisPanel = 'filter' | 'selection' | null")
    expect(store).toContain('activeGisPanel: null as GisPanel')
    expect(store).not.toContain('filterDrawerOpen')
    expect(store).not.toContain('analysisDrawerOpen')
    expect(store).not.toContain('polygonPreviewOpen')
    expect(shell).toContain("mapStore.openGisPanel('filter')")
    expect(shell).not.toContain("mapStore.openGisPanel('analytics')")
    expect(shell).not.toContain("mapStore.openGisPanel('assistant')")
  })

  it('keeps the filter in the mobile bar and moves creation to an authenticated FAB', () => {
    const shell = appFile('components/layout/AppShell.vue')
    const padding = appFile('utils/mapViewportPadding.ts')
    const actionBar = shell.slice(shell.indexOf('<nav'), shell.indexOf('</nav>'))
    expect(padding).toContain('top: 56')
    expect(padding).not.toContain('top: 104')
    expect(actionBar.match(/<button class="map-action"/g)).toHaveLength(1)
    expect(actionBar).toContain('aria-label="Filter öffnen"')
    expect(actionBar).not.toContain('aria-label="Analyse öffnen"')
    expect(actionBar).not.toContain('/flaechen/neu')
    expect(shell).toContain('grid-template-columns: minmax(0, 1fr)')
    expect(shell).toContain('@media (min-width: 480px)')
    expect(shell).toContain('grid-template-columns: max-content')
    expect(shell).not.toContain('grid-column: 1 / -1')
    expect(shell).toContain('data-mobile-create-fab')
    expect(shell).toContain('v-if="authStore.authenticated && (mapStore.activeGisPanel === null || isCompact)"')
    expect(shell).toContain('to="/flaechen/neu"')
    expect(shell).toContain('aria-label="Neue Fläche anlegen"')
    expect(shell).toContain('bottom: calc(env(safe-area-inset-bottom) + 6.5rem)')
    expect(shell).toContain('width: 3.25rem; height: 3.25rem')
    expect(shell).toContain('@media (min-width: 1024px) { .mobile-create-fab { display: none; } }')
  })

  it('docks a bounded, non-modal panel beside the map in the compact workbench', () => {
    const shell = appFile('components/layout/AppShell.vue')
    const panel = appFile('components/layout/GisToolPanel.vue')
    const map = mapHostSource()
    expect(shell).toContain("grid-template-columns: minmax(0, 1fr) clamp(340px, 34vw, 420px)")
    expect(shell).toContain('data-gis-map-stage')
    expect(panel).toContain('data-gis-tool-panel')
    expect(shell).toContain('mapStore.activeGisPanel === null || isCompact')
    expect(panel).toContain('overflow-y-auto overscroll-contain')
    expect(panel).not.toContain('bg-slate-950/30')
    expect(map).toContain('createResizeObserver: handler => new ResizeObserver(handler)')
    expect(map).toContain('this.#resizeObserver.observe(container)')
  })

  it('keeps the bottom-sheet backdrop exclusive to the mobile component', () => {
    const shell = appFile('components/layout/AppShell.vue')
    const sheet = appFile('components/ui/AppBottomSheet.vue')
    const panel = appFile('components/layout/GisToolPanel.vue')
    expect(shell).toContain(':open="isMobile && mapStore.activeGisPanel !== null"')
    expect(sheet).toContain('bg-slate-950/30')
    expect(panel).not.toContain('bg-slate-950/30')
  })

  it('keeps preview navigation slug-based and OSM data on demand', () => {
    const preview = appFile('components/analysis/PolygonStatistics.vue')
    const store = appFile('stores/polygon.ts')
    expect(preview).toContain('/flaechen/${polygon.slug}')
    expect(preview).toContain(':info="store.selectedOsmInfo"')
    expect(store).toContain('api.osmBySlug(polygon.slug)')
  })

  it('provides accessible modal, focus and browser-back behavior', () => {
    const sheet = appFile('components/ui/AppBottomSheet.vue')
    const shell = appFile('components/layout/AppShell.vue')
    const panel = appFile('components/layout/GisToolPanel.vue')
    expect(sheet).toContain('role="dialog"')
    expect(sheet).toContain('aria-modal="true"')
    expect(sheet).toContain(':aria-labelledby="titleId"')
    expect(sheet).toContain("event.key === 'Escape'")
    expect(sheet).toContain("event.key !== 'Tab'")
    expect(sheet).toContain('returnFocusTo?.focus()')
    expect(panel).toContain('<aside')
    expect(panel).not.toContain('aria-modal')
    expect(panel).not.toContain("event.key !== 'Tab'")
    expect(panel).toContain("event.key === 'Escape'")
    expect(panel).toContain('returnFocusTo?.focus')
    expect(shell).toContain("window.addEventListener('popstate'")
    expect(shell).not.toContain('requestResize')
  })

  it('shares medium and expanded snap points, gestures and one scroll container', () => {
    const sheet = appFile('components/ui/AppBottomSheet.vue')
    expect(sheet).toContain("value === 'expanded'")
    expect(sheet).toContain('height * 0.94')
    expect(sheet).toContain('height * 0.6')
    expect(sheet).toContain('data-sheet-drag-handle')
    expect(sheet).toContain('data-sheet-scroll')
    expect(sheet).toContain('scroller.value?.scrollTop !== 0')
    expect(sheet).toContain('overscroll-contain')
    expect(sheet).toContain('isInteractiveTarget')
    expect(sheet).toContain('@touchmove="continueContentTouch"')
    expect(sheet).toContain('event.preventDefault()')
    expect(sheet).not.toContain('storedScrollPositions')
    expect(sheet).toContain('props.contentKey')
  })

  it('resets only newly opened or identity-changed sheet content to the top', () => {
    const sheet = appFile('components/ui/AppBottomSheet.vue')
    const shell = appFile('components/layout/AppShell.vue')
    expect(sheet).toContain("watch([() => props.open, () => props.contentKey]")
    expect(sheet).toContain('shouldResetBottomSheetScroll(open, wasOpen, contentKey, previousContentKey)')
    expect(sheet).toContain('resetBottomSheetScroll(() => scroller.value)')
    expect(sheet).not.toContain("behavior: 'smooth'")
    expect(sheet).not.toContain('window.scrollTo')
    expect(shell).toContain("return `polygon:${entity.id}`")
    expect(shell).toContain('return `osm:${entity.feature.properties.osm_type}:${entity.feature.properties.osm_id}`')
    expect(shell).toContain('return `module:${mapStore.runtimeSelection.moduleId}:${mapStore.runtimeSelection.featureId}`')
  })

  it('uses identical safe-area, animation and reduced-motion handling', () => {
    const sheet = appFile('components/ui/AppBottomSheet.vue')
    expect(sheet).toContain('env(safe-area-inset-bottom)')
    expect(sheet).toContain("maxHeight: 'calc(100dvh - 0.5rem)'")
    expect(sheet).toContain("window.visualViewport?.addEventListener('resize'")
    expect(sheet).toContain("(scroller.value?.scrollTop || 0) === 0")
    expect(sheet).toContain('transition: height 250ms ease-out, transform 250ms ease-out')
    expect(sheet).toContain('@media (prefers-reduced-motion: reduce)')
  })

  it('uses visible loading and retryable error states', () => {
    const map = mapHostSource()
    expect(map).toContain('Karte wird geladen')
    expect(map).toContain('Karte konnte nicht geladen werden.')
    expect(map).toContain('Erneut versuchen')
  })

  it('keeps public GIS controls read-only, understandable and at least 44 pixels large', () => {
    const shell = appFile('components/layout/AppShell.vue')
    const controls = appFile('components/map/MapControls.vue')
    const preview = appFile('components/analysis/PolygonStatistics.vue')
    const hint = appFile('components/layout/LeftSidebar.vue')
    expect(shell).toContain('aria-label="Filter öffnen"')
    expect(shell).not.toContain('aria-label="Analyse öffnen"')
    expect(shell).toContain('aria-label="Neue Fläche anlegen"')
    expect(shell).toContain('aria-pressed="mapStore.activeGisPanel')
    expect(shell).toContain('height: 2.75rem')
    expect(shell).toContain('border: 1px solid transparent')
    expect(controls.match(/h-11 w-11/g)).toHaveLength(3)
    expect(preview).toContain('Details anzeigen')
    expect(hint).not.toContain('Bearbeitung')
  })

  it('anchors every upper-right map control in one stable container', () => {
    const map = mapHostSource()
    const container = appFile('components/map/MapControlsContainer.vue')
    expect(map).toContain('absolute right-3 top-3')
    expect(map).toContain('<MapControlsContainer')
    expect(map).not.toContain('<MapLayerControl')
    expect(container).toContain('w-11 flex-col')
    expect(container).toContain('<MapControls')
    expect(container).toContain('<MapLayerControl')
  })

  it('keeps the layer button bounding box independent from its open state', () => {
    const layer = appFile('components/map/MapLayerControl.vue')
    expect(layer).toContain('class="relative h-11 w-11"')
    expect(layer).toContain('grid h-11 w-11')
    expect(layer).toContain("'border-slate-200 bg-white text-slate-600'")
    expect(layer).toContain(':aria-expanded="open"')
    expect(layer).toContain('class="absolute bottom-0 right-[calc(100%+0.5rem)] w-52')
    expect(layer).not.toContain('scale-')
    expect(layer).not.toContain('translate-')
    expect(layer).not.toContain('border-2')
  })

  it('keeps mobile create and detail maps large and touch-editable', () => {
    const createMap = appFile('components/polygon/PolygonCreateMap.vue')
    const detailMap = appFile('components/polygon/PolygonDetailMap.vue')
    expect(createMap).toContain('h-[clamp(320px,50dvh,520px)]')
    expect(detailMap).toContain('h-[clamp(320px,46dvh,480px)]')
    expect(detailMap).toContain('touchZoomRotate.disable()')
    expect(detailMap).toContain('touchZoomRotate.enable()')
  })

  it('does not hide horizontal overflow globally as a layout workaround', () => {
    const css = appFile('assets/css/main.css')
    expect(css).not.toMatch(/body\s*\{[^}]*overflow-x:\s*hidden/s)
  })

  it('keeps fixed mobile navigation anchored while it animates', () => {
    const css = appFile('assets/css/main.css')
    const navigationTransition = css.match(/\.mobile-navigation-enter-from,\s*\.mobile-navigation-leave-to\s*\{([^}]*)\}/s)?.[1] || ''
    expect(navigationTransition).toContain('opacity: 0')
    expect(navigationTransition).not.toContain('transform')
    expect(css).toContain('body.mobile-nav-open')
  })
})
