"""Öffentliche Contracts der Backend-Module-Plattform."""

from app.platform.modules.contracts import (
    ModuleDefinition,
    ModuleDiscoveryProvider,
    ModuleLifecycleHook,
    ModuleRegistrationContext,
)
from app.platform.modules.dependency_graph import resolve_module_order
from app.platform.modules.discovery import (
    ENTRY_POINT_GROUP,
    EntryPointModuleDiscovery,
    FirstPartyModuleDiscovery,
)
from app.platform.modules.errors import (
    DuplicateConfigNamespaceError,
    DuplicateModuleIdError,
    DuplicatePersistenceSchemaError,
    InvalidRuntimeVersionError,
    MissingModuleDependencyError,
    ModuleCompatibilityError,
    ModuleDependencyCycleError,
    ModuleDependencyError,
    ModuleDependencyVersionError,
    ModuleDiscoveryError,
    ModuleLoadError,
    ModuleManifestError,
    ModulePersistenceError,
    ModuleRegistrationError,
    ModuleRuntimeError,
    ModuleSelfDependencyError,
    ModuleShutdownError,
    ModuleStartupError,
    ModuleValidationError,
    UnsupportedManifestVersionError,
)
from app.platform.modules.manifest import (
    ModuleBackendPackage,
    ModuleConfig,
    ModuleFrontendPackage,
    ModuleManifestV1,
    ModuleOptionalRequirements,
    ModulePersistence,
    ModuleRequirements,
    module_manifest_json_schema,
    parse_manifest,
    validate_manifest,
    validate_manifests,
)
from app.platform.modules.runtime import (
    MODULE_SDK_VERSION,
    ModuleRecord,
    ModuleRegistry,
    ModuleRuntime,
    create_module_runtime,
    resolve_module_definitions,
)
from app.platform.modules.sdk import (
    BackendModule,
    ModuleContext,
    ModuleMigrationSource,
    ModulePersistenceContribution,
)

__all__ = [
    "ENTRY_POINT_GROUP",
    "MODULE_SDK_VERSION",
    "BackendModule",
    "DuplicateConfigNamespaceError",
    "DuplicateModuleIdError",
    "DuplicatePersistenceSchemaError",
    "EntryPointModuleDiscovery",
    "FirstPartyModuleDiscovery",
    "InvalidRuntimeVersionError",
    "MissingModuleDependencyError",
    "ModuleBackendPackage",
    "ModuleCompatibilityError",
    "ModuleConfig",
    "ModuleContext",
    "ModuleDefinition",
    "ModuleDependencyCycleError",
    "ModuleDependencyError",
    "ModuleDependencyVersionError",
    "ModuleDiscoveryError",
    "ModuleDiscoveryProvider",
    "ModuleFrontendPackage",
    "ModuleLifecycleHook",
    "ModuleLoadError",
    "ModuleManifestError",
    "ModuleManifestV1",
    "ModuleMigrationSource",
    "ModuleOptionalRequirements",
    "ModulePersistence",
    "ModulePersistenceContribution",
    "ModulePersistenceError",
    "ModuleRecord",
    "ModuleRegistrationContext",
    "ModuleRegistrationError",
    "ModuleRegistry",
    "ModuleRequirements",
    "ModuleRuntime",
    "ModuleRuntimeError",
    "ModuleSelfDependencyError",
    "ModuleShutdownError",
    "ModuleStartupError",
    "ModuleValidationError",
    "UnsupportedManifestVersionError",
    "create_module_runtime",
    "module_manifest_json_schema",
    "parse_manifest",
    "resolve_module_definitions",
    "resolve_module_order",
    "validate_manifest",
    "validate_manifests",
]
