<template>
  <ContentPageShell v-if="authorized" :title="campaign?.internal_name || 'Rundmail'" description="Entwurf prüfen, Testmail senden und den Versand ausdrücklich bestätigen." eyebrow="E-Mail-Zentrale" :breadcrumbs="[{ label: 'Rundmails', to: '/admin/email-zentrale/rundmails' }, { label: campaign?.internal_name || 'Rundmail' }]" max-width="wide">
    <EmailCenterTabs />
    <p v-if="message" class="mb-4 rounded-xl bg-emerald-50 p-4 text-emerald-900" role="status">{{ message }}</p><p v-if="error" class="mb-4 rounded-xl bg-rose-50 p-4 text-rose-800" role="alert">{{ error }}</p>
    <EmailCampaignForm v-if="campaign && campaign.status === 'DRAFT'" v-model="campaign" :busy="busy" submit-label="Entwurf speichern" @submit="save" />
    <Card v-else-if="campaign" class="p-6"><p class="font-bold">Status: {{ campaign.status }}</p><p class="mt-2 text-sm">{{ campaign.sent_count }} / {{ campaign.recipient_count }} versendet · {{ campaign.failed_count }} fehlgeschlagen</p></Card>
    <div v-if="campaign" class="mt-5 flex flex-wrap gap-3"><Button :disabled="busy" @click="previewMail">Vorschau</Button><Button :disabled="busy" @click="testMail">Testmail an mich</Button><Button v-if="campaign.status === 'DRAFT'" variant="primary" :disabled="busy" @click="prepareStart">Versand vorbereiten</Button><Button v-if="['SCHEDULED', 'PROCESSING'].includes(campaign.status)" variant="ghost" :disabled="busy" @click="cancel">Versand abbrechen</Button></div>
    <AppModal :open="Boolean(preview)" title="Rundmail-Vorschau" size="xl" @update:open="value => { if (!value) preview = null }" @close="preview = null"><template v-if="preview"><p class="mb-4"><strong>Betreff:</strong> {{ preview.subject }}</p><div class="grid gap-6 lg:grid-cols-2"><section><h3 class="mb-2 font-bold">Desktop-Vorschau</h3><iframe class="h-[32rem] w-full rounded-xl border" sandbox="" :srcdoc="preview.html" /></section><section><h3 class="mb-2 font-bold">Mobile Vorschau</h3><iframe class="mx-auto h-[32rem] w-full max-w-[390px] rounded-xl border" sandbox="" :srcdoc="preview.html" /></section></div><details class="mt-5"><summary>Text-Version</summary><pre class="mt-3 whitespace-pre-wrap bg-slate-100 p-4">{{ preview.text }}</pre></details></template></AppModal>
    <AppModal :open="confirmOpen" title="Rundmail versenden?" @update:open="confirmOpen = $event" @close="confirmOpen = false"><p>Diese Rundmail wird an <strong>{{ recipientCount }}</strong> Benutzer versendet.</p><dl class="mt-4 grid grid-cols-[auto_1fr] gap-2 text-sm"><dt>Typ</dt><dd>{{ campaign?.campaign_type }}</dd><dt>Zielgruppe</dt><dd>{{ campaign?.recipient_scope }}</dd><dt>Betreff</dt><dd>{{ campaign?.subject }}</dd></dl><label v-if="campaign?.campaign_type === 'LEGAL'" class="mt-5 flex gap-3"><input v-model="legalConfirmed" type="checkbox"><span>Ich bestätige die Klassifizierung dieser Nachricht als notwendige Mitteilung. Newsletter-Abmeldungen werden ignoriert.</span></label><div class="mt-6 flex justify-end gap-3"><Button @click="confirmOpen = false">Abbrechen</Button><Button variant="primary" :disabled="campaign?.campaign_type === 'LEGAL' && !legalConfirmed" @click="start">{{ recipientCount }} E-Mails versenden</Button></div></AppModal>
  </ContentPageShell>
</template>

<script setup lang="ts">
import type { EmailCampaign, EmailCampaignPreview } from '~/types/admin'
definePageMeta({ middleware: 'superuser' })
const auth = useAuthStore(); const router = useRouter(); const route = useRoute(); const api = useEmailCampaigns(); const authorized = ref(false); const busy = ref(false); const error = ref(''); const message = ref(''); const campaign = ref<EmailCampaign | null>(null); const preview = ref<EmailCampaignPreview | null>(null); const confirmOpen = ref(false); const recipientCount = ref(0); const legalConfirmed = ref(false)
async function action(run: () => Promise<void>) { busy.value = true; error.value = ''; message.value = ''; try { await run() } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Die Aktion ist fehlgeschlagen.' } finally { busy.value = false } }
const save = () => action(async () => { campaign.value = await api.save(campaign.value!); message.value = 'Der Entwurf wurde gespeichert.' })
const previewMail = () => action(async () => { preview.value = await api.preview(campaign.value!.id) })
const testMail = () => action(async () => { message.value = (await api.testSend(campaign.value!.id)).message })
const prepareStart = () => action(async () => { recipientCount.value = (await api.recipientCount(campaign.value!.id)).recipient_count; confirmOpen.value = true })
const start = () => action(async () => { campaign.value = await api.start(campaign.value!.id, legalConfirmed.value); confirmOpen.value = false; message.value = 'Der asynchrone Versand wurde gestartet.' })
const cancel = () => action(async () => { campaign.value = await api.cancel(campaign.value!.id); message.value = 'Ausstehende Zustellungen wurden abgebrochen.' })
let refreshTimer: ReturnType<typeof setInterval> | undefined
onMounted(async () => { if (!auth.initialized) await auth.initialize(); if (!auth.user?.is_superuser) return router.replace('/'); authorized.value = true; await action(async () => { campaign.value = await api.load(String(route.params.id)) }); refreshTimer = setInterval(async () => { if (campaign.value && ['SCHEDULED', 'PROCESSING'].includes(campaign.value.status)) { try { campaign.value = await api.load(campaign.value.id) } catch { error.value = 'Der Versandstatus konnte nicht aktualisiert werden.' } } }, 15_000) })
onUnmounted(() => clearInterval(refreshTimer))
usePageSeo({ title: 'Rundmail bearbeiten', description: 'Rundmail prüfen und versenden.', path: `/admin/email-zentrale/rundmails/${route.params.id}`, robots: 'noindex,nofollow', openGraph: false, twitter: false, structuredData: false })
</script>
